AllCops:
  NewCops: enable
  Exclude:
    - Guardfile
  SuggestExtensions: false
Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 15
Metrics/BlockLength:
  Max: 30
  Exclude:
    - ./spec/board_spec.rb
    - ./spec/game_spec.rb
    - ./spec/players_spec.rb
    - ./spec/console_spec.rb
    - ./spec/easy_ai_spec.rb
Layout/LineLength:
  Exclude: 
    - ./spec/console_spec.rb
Style/Documentation: 
  Enabled: false