AllCops:
  NewCops: enable
  Exclude:
    - Guardfile
  SuggestExtensions: false
Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Max: 30
  Exclude:
    - ./spec/board_spec.rb
Layout/LineLength:
  Exclude: 
    - ./spec/console_spec.rb
Lint/UselessAssignment:
  Exclude: 
    - ./lib/main.rb
    - ./spec/game_spec.rb
Style/Documentation: 
  Enabled: false