AllCops:
  NewCops: enable
  Exclude:
    - Guardfile
  SuggestExtensions: false
Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Max: 30
  Exclude:
    - ./spec/board_spec.rb
    - ./spec/game_spec.rb
    - ./spec/players_spec.rb
    - ./spec/console_spec.rb
    - ./spec/easy_ai_spec.rb
    - ./spec/win_finder_spec.rb
    - ./spec/input_validator_spec.rb
    - ./spec/game_builder_spec.rb
    - ./spec/player_builder_spec.rb
    - ./spec/easy_ai_player_spec.rb
    - ./spec/player_selector_spec.rb
Layout/LineLength:
  Exclude: 
    - ./spec/console_spec.rb
Style/Documentation: 
  Enabled: false